---


- hosts: '{{ host }}'


  gather_facts: yes
    
  remote_user: staging
  become: yes 
  become_method: sudo
  vars:
      app_base_path: "/home/devhome/"
  


- name: Create folder and file
  hosts: staging
  become: yes
  tasks:
    - name: Create directory if it doesn't exist
      ansible.builtin.file:
        path: /path/to/folder
        state: directory
        mode: '0755'

    - name: Create a file inside the directory
      ansible.builtin.file:
        path: /path/to/folder/example_file.txt
        state: touch
